#! /usr/bin/env bash

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

cd $HOME;
info "basic Deps"
sudo apt-get install curl zsh vim git build-essential libssl-dev -y
success "basic deps installed"

info "install dotfiles repo"
git clone https://github.com/therebelrobot/dotfiles $HOME/.dotfiles
DOTFILES_ROOT=$HOME/.dotfiles
success "dotfiles cloned"

info "install ohmyzsh and change default shell to zsh"
curl -L http://install.ohmyz.sh | sh
sudo sed -i "s/auth       required   pam_shells.so/# auth       required   pam_shells.so/g" /etc/pam.d/chsh
chsh -s $(which zsh);
success "ohmyzsh installed"

info "link .zshrc"
mv $HOME/.zshrc $HOME/.zshrc.ohmyzsh
ln -s $DOTFILES_ROOT/home.zshrc $HOME/.zshrc
success ".zshrc now linked"

info "link .gitconfig"
ln -s $DOTFILES_ROOT/.gitconfig $HOME/.gitconfig
success "gitconfig installed"

info "link Vundle and .vimrc"
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
ln -s $DOTFILES_ROOT/.vimrc $HOME/.vimrc
success "Vundle and .vimrc Installed"

info "Installing Node and Node Modules"
curl https://raw.githubusercontent.com/creationix/nvm/v0.22.0/install.sh | bash
source $HOME/.nvm/nvm.sh
nvm install 0.10
nvm use 0.10 --defualt
npm install -g gulp grunt-cli slush nodemon bower vtop browserify watchify
success "Installed Node and Node Modules"

info "Installing Nginx"
sudo add-apt-repository ppa:nginx/stable
sudo apt-get update
sudo apt-get install nginx
success "Installed Nginx"

info "Installing Ack"
sudo apt-get install ack-grep
sudo dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
info "Installed Ack"

info "Setting up SSH"
mkdir $HOME/.ssh
touch $HOME/config
echo "Building SSH key. What is the name of your system?"
read COMPNAME
ssh-keygen -t rsa -C "$COMPNAME"
info "SSH PUBLIC KEY: "
cat $HOME/id_rsa.pub

success "Thank you for installing Dotfiles. Have a great day!"

