#! /usr/bin/env bash

cd $HOME;
echo "basic Deps"
echo "install xcode command line"
xcode-select --install
echo "command line tools installed"

echo "install Brew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew update
brew upgrade
echo "Brew installed"

brew install curl zsh vim --with-lua gcc
echo "basic deps installed"

echo "install dotfiles repo"
git clone git@github.com:therebelrobot/dotfiles.git $HOME/.dotfiles
echo "dotfiles cloned"

echo "install ohmyzsh and change default shell to zsh"
curl -L http://install.ohmyz.sh | sh
sudo sed -i "s/auth       required   pam_shells.so/# auth       required   pam_shells.so/g" /etc/pam.d/chsh
chsh -s $(which zsh);
echo "ohmyzsh installed"

echo "link .zshrc"
mv $HOME/.zshrc $HOME/.zshrc.ohmyzsh
ln -s $HOME/.dotfiles/home.zshrc $HOME/.zshrc
echo ".zshrc installed"

echo "link .gitconfig"
ln -s $HOME/.dotfiles/.gitconfig $HOME/.gitconfig
echo ".gitconfig installed"

echo "link .gitignore"
ln -s $HOME/.dotfiles/.gitignore $HOME/.gitignore
echo ".gitignore installed"

echo "link .editorconfig"
ln -s $HOME/.dotfiles/.editorconfig $HOME/.editorconfig
echo ".editorconfig installed"

echo "link Vundle and .vimrc"
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
ln -s $HOME/.dotfiles/.vimrc $HOME/.vimrc
echo "Vundle and .vimrc Installed"

echo "Installing Node and Node Modules"
curl https://raw.githubusercontent.com/creationix/nvm/v0.22.0/install.sh | bash
source $HOME/.nvm/nvm.sh
nvm install iojs
nvm use iojs --defualt
npm install -g gulp grunt-cli slush nodemon bower vtop browserify watchify mocha istanbul httpsnippet keybase-installer
keybase-installer
echo "Installed Node and Node Modules"

echo "Installing Nginx"
brew install nginx
sudo cp /usr/local/opt/nginx/*.plist /Library/LaunchDaemons/
sudo chown root:wheel /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
mkdir -p /usr/local/etc/nginx/logs
mkdir -p /usr/local/etc/nginx/sites-available
mkdir -p /usr/local/etc/nginx/sites-enabled
mkdir -p /usr/local/etc/nginx/conf.d
mkdir -p /usr/local/etc/nginx/ssl
sudo mkdir -p /var/www
sudo chown :staff /var/www
sudo chmod 775 /var/www
rm /usr/local/etc/nginx/nginx.conf
ln -s $HOME/.dotfiles/nginx.conf /usr/local/etc/nginx/nginx.conf
sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
echo "Installed Nginx"

echo "Installing MySQL"
brew install mysql
ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
mysql_secure_installation
echo "Installed MySQL"

echo "Installing Ack"
brew install ack
echo "Installed Ack"

echo "building folders for projects"
mkdir git git/personal git/opensource git/work git/other
mkdir ISOs ISOs/OS ISOs/OS/Linux ISOs/OS/Windows ISOs/OS/Mac
mkdir fonts

echo "Setting up SSH"
mkdir $HOME/.ssh
touch $HOME/config
echo "Building SSH key. What is the name of your system?"
read COMPNAME
ssh-keygen -t rsa -C "$COMPNAME"
echo "SSH PUBLIC KEY: "
cat $HOME/id_rsa.pub

echo "Thank you for installing Dotfiles. Have a great day!"
